import { describe, expect, test } from 'vitest'
import { toSafeUnicode } from '../src/toSafeUnicode.js'

describe('toSafeUnicode', () => {
  test("test safe unicode", () => {
    expect(toSafeUnicode("\0")).toBe("")
    expect(toSafeUnicode("\t")).toBe("\t")
    expect(toSafeUnicode("\r")).toBe("\r")
    expect(toSafeUnicode("\n")).toBe("\n")
    expect(toSafeUnicode(" ")).toBe(" ")
    expect(toSafeUnicode("A")).toBe("A")
    expect(toSafeUnicode("a")).toBe("a")
    expect(toSafeUnicode("0")).toBe("0")
    expect(toSafeUnicode(".")).toBe(".")
    expect(toSafeUnicode("@")).toBe("@")
    expect(toSafeUnicode("\x7F")).toBe("")
    expect(toSafeUnicode("あ")).toBe("あ")
    expect(toSafeUnicode("ア")).toBe("ア")
    expect(toSafeUnicode("ｱ")).toBe("ｱ")
    expect(toSafeUnicode("亜")).toBe("亜")
    expect(toSafeUnicode("\uD800")).toBe("")
    expect(toSafeUnicode("\uDC00")).toBe("")
    expect(toSafeUnicode("\uD800\uDC00")).toBe("\uD800\uDC00")
    expect(toSafeUnicode("\uFDD0")).toBe("")
    expect(toSafeUnicode("\uFDEF")).toBe("")
    expect(toSafeUnicode("\uFEF0")).toBe("\uFEF0")
    expect(toSafeUnicode("\uFEFF")).toBe("")
    expect(toSafeUnicode("\uFFF0")).toBe("")
    expect(toSafeUnicode("\uFFFE")).toBe("")
    expect(toSafeUnicode("\uFFFF")).toBe("")
    expect(toSafeUnicode("\u{1FFFE}")).toBe("")
    expect(toSafeUnicode("\u{1FFFF}")).toBe("")
    expect(toSafeUnicode("\u{10FFFE}")).toBe("")
    expect(toSafeUnicode("\u{10FFFF}")).toBe("")
  })
})
