import { describe, expect, test } from 'vitest'
import { toZenginKatakana } from '../src/toZenginKatakana.js'

describe('toZenginKatakana', () => {
  test("test full width", () => {
    expect(toZenginKatakana("\0")).toBe("\0")
    expect(toZenginKatakana(",")).toBe(".")
    expect(toZenginKatakana("，")).toBe(".")
    expect(toZenginKatakana("．")).toBe(".")
    expect(toZenginKatakana("、")).toBe(".")
    expect(toZenginKatakana("。")).toBe(".")
    expect(toZenginKatakana("・")).toBe(".")
    expect(toZenginKatakana("ー")).toBe("-")
    expect(toZenginKatakana("－")).toBe("-")
    expect(toZenginKatakana("／")).toBe("/")
    expect(toZenginKatakana("＼")).toBe("\\")
    expect(toZenginKatakana("￥")).toBe("\\")
    expect(toZenginKatakana("(")).toBe("(")
    expect(toZenginKatakana(")")).toBe(")")
    expect(toZenginKatakana("[")).toBe("(")
    expect(toZenginKatakana("]")).toBe(")")
    expect(toZenginKatakana("（")).toBe("(")
    expect(toZenginKatakana("）")).toBe(")")
    expect(toZenginKatakana("［")).toBe("(")
    expect(toZenginKatakana("］")).toBe(")")
    expect(toZenginKatakana("｛")).toBe("(")
    expect(toZenginKatakana("｝")).toBe(")")
    expect(toZenginKatakana("！")).toBe("！")
    expect(toZenginKatakana("０")).toBe("0")
    expect(toZenginKatakana("Ａ")).toBe("A")
    expect(toZenginKatakana("ａ")).toBe("A")
    expect(toZenginKatakana("～")).toBe("～")
    expect(toZenginKatakana("亜")).toBe("亜")
    expect(toZenginKatakana("ア")).toBe("ｱ")
    expect(toZenginKatakana("ｱ")).toBe("ｱ")
    expect(toZenginKatakana("ガ")).toBe("ｶﾞ")
    expect(toZenginKatakana("ｶﾞ")).toBe("ｶﾞ")
    expect(toZenginKatakana("パ")).toBe("ﾊﾟ")
    expect(toZenginKatakana("ﾊﾟ")).toBe("ﾊﾟ")
    expect(toZenginKatakana("「")).toBe("｢")
    expect(toZenginKatakana("」")).toBe("｣")
  })
})
