import { describe, expect, test } from "vitest"
import { toSafeUnicode } from "../../src/text/toSafeUnicode.js"

describe('toSafeUnicode', () => {
  test("test safe unicode", () => {
    expect(toSafeUnicode("\0")).toBe("")
    expect(toSafeUnicode("\t")).toBe("\t")
    expect(toSafeUnicode("\r")).toBe("\n")
    expect(toSafeUnicode("\n")).toBe("\n")
    expect(toSafeUnicode("\r\n")).toBe("\n")
    expect(toSafeUnicode(" ")).toBe(" ")
    expect(toSafeUnicode("A")).toBe("A")
    expect(toSafeUnicode("a")).toBe("a")
    expect(toSafeUnicode("0")).toBe("0")
    expect(toSafeUnicode(".")).toBe(".")
    expect(toSafeUnicode("@")).toBe("@")
    expect(toSafeUnicode("\x7F")).toBe("")
    expect(toSafeUnicode("あ")).toBe("あ")
    expect(toSafeUnicode("ぁ")).toBe("ぁ")
    expect(toSafeUnicode("\u3046\u3099")).toBe("ゔ")
    expect(toSafeUnicode("\u304B\u3099")).toBe("が")
    expect(toSafeUnicode("\u306F\u309A")).toBe("ぱ")
    expect(toSafeUnicode("ア")).toBe("ア")
    expect(toSafeUnicode("ァ")).toBe("ァ")
    expect(toSafeUnicode("\u30A6\u3099")).toBe("ヴ")
    expect(toSafeUnicode("\u30AB\u3099")).toBe("ガ")
    expect(toSafeUnicode("\u30CF\u309A")).toBe("パ")
    expect(toSafeUnicode("\u30F2\u3099")).toBe("ヺ")
    expect(toSafeUnicode("ｱ")).toBe("ｱ")
    expect(toSafeUnicode("ｧ")).toBe("ｧ")
    expect(toSafeUnicode("亜")).toBe("亜")
    expect(toSafeUnicode("\uD800")).toBe("")
    expect(toSafeUnicode("\uDC00")).toBe("")
    expect(toSafeUnicode("\uD800\uDC00")).toBe("\uD800\uDC00")
    expect(toSafeUnicode("\uFDD0")).toBe("")
    expect(toSafeUnicode("\uFDEF")).toBe("")
    expect(toSafeUnicode("\uFEF0")).toBe("\uFEF0")
    expect(toSafeUnicode("\uFEFF")).toBe("")
    expect(toSafeUnicode("\uFFF0")).toBe("")
    expect(toSafeUnicode("\uFFFE")).toBe("")
    expect(toSafeUnicode("\uFFFF")).toBe("")
    expect(toSafeUnicode("\u{1FFFE}")).toBe("")
    expect(toSafeUnicode("\u{1FFFF}")).toBe("")
    expect(toSafeUnicode("\u{10FFFE}")).toBe("")
    expect(toSafeUnicode("\u{10FFFF}")).toBe("")
  })
})
